export const getRootPath = () => '/'
export const getLoginPath = () => '/login'
export const getProgressPath = () => '/progress'
export const getSettingsPath = () => '/settings'
export const getOnboardingPath = () => '/onboarding'
