import type { CatalogEntry, RoomEntry } from './types'

// The catalog: one unlock per day for 30 days, then weekly, then monthly.
export const CATALOG: readonly CatalogEntry[] = [
  {
    day: 0,
    kind: 'start',
    text: 'Loose long-sleeve top, joggers, scuffed sneakers with untied laces, messy hair. Hands in pockets, weight on one leg.',
  },
  { day: 1, kind: 'clothes', text: 'Laces tied' },
  { day: 2, kind: 'grooming', text: 'Hair combed' },
  { day: 3, kind: 'clothes', text: 'Sleeves pushed up' },
  { day: 4, kind: 'clothes', text: 'Top smoothed out, creases gone' },
  { day: 5, kind: 'clothes', text: 'Front of the top tucked in' },
  { day: 6, kind: 'clothes', text: 'Belt' },
  { day: 7, kind: 'pose', text: 'Hands out of pockets, arms relaxed' },
  { day: 8, kind: 'accessory', text: 'Watch' },
  { day: 9, kind: 'accessory', text: 'Water bottle in hand' },
  { day: 10, kind: 'clothes', text: 'Joggers swapped for straight trousers' },
  { day: 11, kind: 'accessory', text: 'Keys clipped to the belt loop' },
  { day: 12, kind: 'clothes', text: 'Fitted tee instead of the baggy top' },
  { day: 13, kind: 'accessory', text: 'Wristband' },
  { day: 14, kind: 'grooming', text: 'Haircut, shorter sides' },
  { day: 15, kind: 'clothes', text: 'Clean white sneakers' },
  { day: 16, kind: 'accessory', text: 'Small crossbody bag' },
  {
    day: 17,
    kind: 'accessory',
    text: 'Bag strap shortened, the bag sits higher',
  },
  { day: 18, kind: 'clothes', text: 'Trouser hems cuffed' },
  { day: 19, kind: 'clothes', text: 'Tee in a more confident color' },
  { day: 20, kind: 'grooming', text: 'Hair styled' },
  {
    day: 21,
    kind: 'pose',
    text: 'Arms loosely crossed, bottle set down at the feet',
  },
  { day: 22, kind: 'clothes', text: 'Accent stripe on the sneakers' },
  { day: 23, kind: 'clothes', text: 'Darker, better-fitting trousers' },
  { day: 24, kind: 'accessory', text: 'Thin chain necklace' },
  { day: 25, kind: 'clothes', text: 'Henley with a button placket' },
  { day: 26, kind: 'accessory', text: 'Notebook beside the bottle' },
  { day: 27, kind: 'clothes', text: 'Colored socks showing at the cuff' },
  { day: 28, kind: 'accessory', text: 'Headphones around the neck' },
  { day: 29, kind: 'pose', text: 'Weight even on both feet' },
  { day: 30, kind: 'clothes', text: 'Light jacket tied around the waist' },
  { day: 35, kind: 'grooming', text: 'Hair a little fuller on top' },
  { day: 42, kind: 'pose', text: 'One hand in pocket, relaxed' },
  { day: 49, kind: 'clothes', text: 'Tapered trousers' },
  { day: 56, kind: 'accessory', text: 'Metal-band watch' },
  {
    day: 66,
    kind: 'accessory',
    text: 'Wristband swapped for a leather bracelet',
  },
  {
    day: 75,
    kind: 'accessory',
    text: 'Minimal backpack on one shoulder replaces the crossbody bag',
  },
  { day: 90, kind: 'pose', text: 'Hands on hips, briefly' },
  { day: 105, kind: 'pose', text: 'Jacket carried over the shoulder' },
  { day: 120, kind: 'clothes', text: 'Collared shirt' },
  { day: 150, kind: 'clothes', text: 'Better jacket, darker and structured' },
  { day: 180, kind: 'clothes', text: 'Coherent deeper palette' },
  { day: 210, kind: 'clothes', text: 'Minimal leather sneakers' },
  { day: 240, kind: 'clothes', text: 'Leather belt' },
  { day: 270, kind: 'clothes', text: 'Pressed trousers with a crease' },
  { day: 300, kind: 'clothes', text: 'Shirt pocket with a pen' },
  { day: 330, kind: 'clothes', text: 'Jacket worn' },
  { day: 365, kind: 'pose', text: 'Composed open stance' },
]

// The room fills in at milestones (earned, kept after a break).
export const ROOM: readonly RoomEntry[] = [
  { day: 7, text: 'Small plant on the floor' },
  { day: 14, text: 'Framed print on the wall' },
  { day: 21, text: 'Floor lamp' },
  { day: 30, text: 'Low shelf with a few books; the plant moves onto it' },
  { day: 42, text: 'Rug' },
  { day: 66, text: 'Desk with an open notebook and a mug' },
  { day: 90, text: 'Window with daylight' },
  { day: 120, text: 'Wall shelf with more books' },
  { day: 180, text: 'The shelf plant has grown bigger' },
  { day: 210, text: 'Rolled exercise mat leaning by the shelf' },
  { day: 270, text: 'Second artwork; the lamp is on with warm light' },
  { day: 365, text: 'Curtains and a warm wall tone: a complete, calm room' },
]
