export function getProgressEmoji(streak: number): string {
  if (streak < 1) return '😶 Start your journey today:'
  if (streak < 7) return '🙂 Good start:'
  if (streak < 14) return '💪 You’re getting stronger:'
  if (streak < 30) return '⚡ Great momentum:'
  if (streak < 45) return '🔥 You’re on fire:'
  if (streak < 60) return '🌟 Impressive consistency:'
  if (streak < 75) return '🚀 Unstoppable progress:'
  if (streak < 90) return '💎 True discipline:'
  if (streak < 120) return '🦾 Iron will:'
  if (streak < 150) return '🧠 Mastering your habit:'
  if (streak < 180) return '🧗‍♂️ Climbing higher:'
  if (streak < 210) return '🥇 Halfway champion:'
  if (streak < 240) return '🐉 You’ve become the dragon:'
  if (streak < 270) return '⚔️ Beyond ordinary:'
  if (streak < 300) return '🌈 Legendary consistency:'
  if (streak < 330) return '🦅 Unbreakable focus:'
  if (streak < 360) return '👑 The master of discipline:'
  return '🕊️ Enlightened — the habit is eternal:'
}
