export const PROGRESS_START_TIMESTAMP = 'PROGRESS_START_TIMESTAMP'
export const PROGRESS_DESCRIPTION = 'PROGRESS_DESCRIPTION'
export const PROGRESS_SESSION_ID = 'PROGRESS_SESSION_ID'
export const PROGRESS_OUTBOX_PREFIX = 'progress_outbox_v1'
