-- Territory map: per-user terrain profile + event ledger + credit/decay RPCs.
-- Contract: memory/projects/the-tab-progress/decisions/2026-09-13-territory-map-contract.md
-- Idempotent: safe to re-run.

BEGIN;

-- 1. Tables ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.map_profiles (
  user_id      uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  width        smallint NOT NULL DEFAULT 40,
  height       smallint NOT NULL DEFAULT 40,
  terrain      text NOT NULL,
  started_at   timestamptz NOT NULL DEFAULT now(),
  decay_cursor date NOT NULL,
  created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.map_events (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  x          smallint NOT NULL CHECK (x BETWEEN 0 AND 39),
  y          smallint NOT NULL CHECK (y BETWEEN 0 AND 39),
  kind       text NOT NULL CHECK (kind IN ('claim', 'restore', 'lose')),
  cost       smallint NOT NULL CHECK (cost >= 0),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS map_events_user_created_idx
  ON public.map_events (user_id, created_at DESC, id DESC);

-- 2. RLS + grants: SELECT own rows only; all writes go through the RPCs ------
ALTER TABLE public.map_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.map_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS map_profiles_select_own ON public.map_profiles;
CREATE POLICY map_profiles_select_own ON public.map_profiles
  FOR SELECT TO authenticated USING (user_id = auth.uid());

DROP POLICY IF EXISTS map_events_select_own ON public.map_events;
CREATE POLICY map_events_select_own ON public.map_events
  FOR SELECT TO authenticated USING (user_id = auth.uid());

REVOKE ALL ON TABLE public.map_profiles FROM anon, authenticated;
REVOKE ALL ON TABLE public.map_events FROM anon, authenticated;
GRANT SELECT ON TABLE public.map_profiles TO authenticated;
GRANT SELECT ON TABLE public.map_events TO authenticated;

DO $$
BEGIN
  EXECUTE format('REVOKE ALL ON SEQUENCE %s FROM anon, authenticated',
                 pg_get_serial_sequence('public.map_events', 'id'));
END
$$;

-- 3. Internal helpers (not callable by app roles) ---------------------------
CREATE OR REPLACE FUNCTION public.map_check_tz(p_tz text)
RETURNS void
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
BEGIN
  IF p_tz IS NULL OR NOT EXISTS (SELECT 1 FROM pg_timezone_names WHERE name = p_tz) THEN
    RAISE EXCEPTION 'invalid timezone';
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.map_check_terrain(p_terrain text)
RETURNS void
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
  v_total CONSTANT int := 40 * 40;
  v_water int;
  v_hard  int;
BEGIN
  IF p_terrain IS NULL OR length(p_terrain) <> v_total OR p_terrain !~ '^[lwh]+$' THEN
    RAISE EXCEPTION 'invalid terrain';
  END IF;
  v_water := v_total - length(replace(p_terrain, 'w', ''));
  v_hard  := v_total - length(replace(p_terrain, 'h', ''));
  IF v_water * 100 < v_total * 8 OR v_water * 100 > v_total * 20 THEN
    RAISE EXCEPTION 'invalid terrain';
  END IF;
  IF v_hard * 100 < v_total * 1 OR v_hard * 100 > v_total * 3 THEN
    RAISE EXCEPTION 'invalid terrain';
  END IF;
  IF v_total - v_water - v_hard < 1 THEN
    RAISE EXCEPTION 'invalid terrain';
  END IF;
END;
$$;

-- Newest owned cell (last event per cell is claim/restore; max created_at,id). NULLs if none.
CREATE OR REPLACE FUNCTION public.map_newest_owned(
  p_uid uuid,
  OUT o_x smallint,
  OUT o_y smallint
)
RETURNS record
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
BEGIN
  SELECT l.x, l.y INTO o_x, o_y
  FROM (
    SELECT DISTINCT ON (e.x, e.y) e.x, e.y, e.kind, e.created_at, e.id
    FROM public.map_events e
    WHERE e.user_id = p_uid
    ORDER BY e.x, e.y, e.created_at DESC, e.id DESC
  ) AS l
  WHERE l.kind IN ('claim', 'restore')
  ORDER BY l.created_at DESC, l.id DESC
  LIMIT 1;
END;
$$;

-- Replays missed days after decay_cursor; O(days) over pre-aggregated per-day seconds.
CREATE OR REPLACE FUNCTION public.map_apply_decay(p_uid uuid, p_tz text)
RETURNS void
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
  v_profile   public.map_profiles%ROWTYPE;
  v_start_day date;
  v_yesterday date;
  v_streak    int := 0;
  v_day       record;
  v_cell      record;
BEGIN
  SELECT * INTO v_profile FROM public.map_profiles WHERE user_id = p_uid;
  IF NOT FOUND THEN
    RETURN;
  END IF;

  v_start_day := (v_profile.started_at AT TIME ZONE p_tz)::date;
  v_yesterday := (now() AT TIME ZONE p_tz)::date - 1;
  IF v_yesterday <= v_profile.decay_cursor OR v_yesterday < v_start_day THEN
    RETURN;
  END IF;

  FOR v_day IN
    SELECT gs.d::date AS d, coalesce(ds.s, 0)::bigint AS s
    FROM generate_series(v_start_day::timestamp, v_yesterday::timestamp, interval '1 day')
      AS gs(d)
    LEFT JOIN (
      SELECT (p.created_at AT TIME ZONE p_tz)::date AS d, sum(p.duration_seconds) AS s
      FROM public.progress p
      WHERE p.user_id = p_uid AND p.created_at >= v_profile.started_at
      GROUP BY 1
    ) AS ds ON ds.d = gs.d::date
    ORDER BY gs.d
  LOOP
    IF v_day.s > 0 THEN
      v_streak := 0;
      CONTINUE;
    END IF;
    v_streak := v_streak + 1;
    IF v_streak <= 3 OR v_day.d <= v_profile.decay_cursor THEN
      CONTINUE;
    END IF;

    SELECT * INTO v_cell FROM public.map_newest_owned(p_uid);
    IF v_cell.o_x IS NULL THEN
      CONTINUE;
    END IF;

    INSERT INTO public.map_events (user_id, x, y, kind, cost, created_at)
    VALUES (p_uid, v_cell.o_x, v_cell.o_y, 'lose', 0,
            ((v_day.d + 1)::timestamp AT TIME ZONE p_tz) - interval '1 second');
  END LOOP;

  UPDATE public.map_profiles SET decay_cursor = v_yesterday WHERE user_id = p_uid;
END;
$$;

CREATE OR REPLACE FUNCTION public.map_credits(
  p_uid uuid,
  p_tz text,
  p_started_at timestamptz,
  OUT earned int,
  OUT spent int,
  OUT today_seconds bigint
)
RETURNS record
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
  v_today date := (now() AT TIME ZONE p_tz)::date;
BEGIN
  SELECT coalesce(sum(ds.s / 3600), 0)::int,
         coalesce(sum(ds.s) FILTER (WHERE ds.d = v_today), 0)::bigint
    INTO earned, today_seconds
  FROM (
    SELECT (p.created_at AT TIME ZONE p_tz)::date AS d,
           greatest(sum(p.duration_seconds), 0)::bigint AS s
    FROM public.progress p
    WHERE p.user_id = p_uid AND p.created_at >= p_started_at
    GROUP BY 1
  ) AS ds;

  SELECT coalesce(sum(e.cost), 0)::int INTO spent
  FROM public.map_events e
  WHERE e.user_id = p_uid AND e.kind IN ('claim', 'restore');
END;
$$;

CREATE OR REPLACE FUNCTION public.map_state(p_uid uuid, p_tz text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
  v_profile public.map_profiles%ROWTYPE;
  v_credits record;
  v_cells   jsonb;
BEGIN
  SELECT * INTO v_profile FROM public.map_profiles WHERE user_id = p_uid;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'terrain required';
  END IF;

  SELECT * INTO v_credits FROM public.map_credits(p_uid, p_tz, v_profile.started_at);

  SELECT coalesce(jsonb_agg(jsonb_build_object(
           'x', l.x, 'y', l.y, 'kind', l.kind, 'cost', l.cost,
           'eventId', l.id, 'createdAt', l.created_at
         ) ORDER BY l.created_at, l.id), '[]'::jsonb)
    INTO v_cells
  FROM (
    SELECT DISTINCT ON (e.x, e.y) e.x, e.y, e.kind, e.cost, e.created_at, e.id
    FROM public.map_events e
    WHERE e.user_id = p_uid
    ORDER BY e.x, e.y, e.created_at DESC, e.id DESC
  ) AS l;

  RETURN jsonb_build_object(
    'profile', jsonb_build_object(
      'width', v_profile.width,
      'height', v_profile.height,
      'terrain', v_profile.terrain,
      'startedAt', v_profile.started_at,
      'decayCursor', v_profile.decay_cursor
    ),
    'credits', jsonb_build_object(
      'earned', v_credits.earned,
      'spent', v_credits.spent,
      'available', v_credits.earned - v_credits.spent,
      'todaySeconds', v_credits.today_seconds
    ),
    'cells', v_cells
  );
END;
$$;

-- 4. Public RPCs (SECURITY DEFINER; per-user advisory lock serializes writes) -
CREATE OR REPLACE FUNCTION public.map_open(p_tz text, p_terrain text DEFAULT NULL)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid uuid;
BEGIN
  v_uid := auth.uid();
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not authenticated';
  END IF;
  PERFORM public.map_check_tz(p_tz);
  PERFORM pg_advisory_xact_lock(hashtextextended(v_uid::text, 0));

  IF NOT EXISTS (SELECT 1 FROM public.map_profiles WHERE user_id = v_uid) THEN
    IF p_terrain IS NULL THEN
      RAISE EXCEPTION 'terrain required';
    END IF;
    PERFORM public.map_check_terrain(p_terrain);
    INSERT INTO public.map_profiles (user_id, terrain, started_at, decay_cursor)
    VALUES (v_uid, p_terrain, now(), (now() AT TIME ZONE p_tz)::date - 1)
    ON CONFLICT (user_id) DO NOTHING;
  END IF;

  PERFORM public.map_apply_decay(v_uid, p_tz);
  RETURN public.map_state(v_uid, p_tz);
END;
$$;

CREATE OR REPLACE FUNCTION public.map_claim(p_tz text, p_x int, p_y int)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid      uuid;
  v_profile  public.map_profiles%ROWTYPE;
  v_char     text;
  v_cost     smallint;
  v_last     text;
  v_kind     text;
  v_owned    int;
  v_adjacent int;
  v_credits  record;
BEGIN
  v_uid := auth.uid();
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not authenticated';
  END IF;
  PERFORM public.map_check_tz(p_tz);
  PERFORM pg_advisory_xact_lock(hashtextextended(v_uid::text, 0));

  SELECT * INTO v_profile FROM public.map_profiles WHERE user_id = v_uid;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'terrain required';
  END IF;

  PERFORM public.map_apply_decay(v_uid, p_tz);

  IF p_x IS NULL OR p_y IS NULL OR p_x < 0 OR p_y < 0
     OR p_x >= v_profile.width OR p_y >= v_profile.height THEN
    RAISE EXCEPTION 'out of bounds';
  END IF;

  v_char := substr(v_profile.terrain, p_y * v_profile.width + p_x + 1, 1);
  IF v_char = 'w' THEN
    RAISE EXCEPTION 'water';
  END IF;
  v_cost := CASE WHEN v_char = 'h' THEN 3 ELSE 1 END;

  SELECT e.kind INTO v_last
  FROM public.map_events e
  WHERE e.user_id = v_uid AND e.x = p_x AND e.y = p_y
  ORDER BY e.created_at DESC, e.id DESC
  LIMIT 1;

  IF v_last = 'lose' THEN
    v_kind := 'restore';
  ELSIF v_last IN ('claim', 'restore') THEN
    RAISE EXCEPTION 'already owned';
  ELSE
    SELECT count(*)::int,
           count(*) FILTER (WHERE abs(l.x - p_x) + abs(l.y - p_y) = 1)::int
      INTO v_owned, v_adjacent
    FROM (
      SELECT DISTINCT ON (e.x, e.y) e.x, e.y, e.kind
      FROM public.map_events e
      WHERE e.user_id = v_uid
      ORDER BY e.x, e.y, e.created_at DESC, e.id DESC
    ) AS l
    WHERE l.kind IN ('claim', 'restore');
    IF v_owned > 0 AND v_adjacent = 0 THEN
      RAISE EXCEPTION 'not adjacent';
    END IF;
    v_kind := 'claim';
  END IF;

  SELECT * INTO v_credits FROM public.map_credits(v_uid, p_tz, v_profile.started_at);
  IF v_credits.earned - v_credits.spent < v_cost THEN
    RAISE EXCEPTION 'not enough cells';
  END IF;

  INSERT INTO public.map_events (user_id, x, y, kind, cost)
  VALUES (v_uid, p_x, p_y, v_kind, v_cost);

  RETURN public.map_state(v_uid, p_tz);
END;
$$;

CREATE OR REPLACE FUNCTION public.map_undo(p_tz text, p_event_id bigint)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid    uuid;
  v_event  public.map_events%ROWTYPE;
  v_newest bigint;
BEGIN
  v_uid := auth.uid();
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not authenticated';
  END IF;
  PERFORM public.map_check_tz(p_tz);
  PERFORM pg_advisory_xact_lock(hashtextextended(v_uid::text, 0));

  SELECT * INTO v_event
  FROM public.map_events
  WHERE id = p_event_id AND user_id = v_uid;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'cannot undo';
  END IF;

  SELECT e.id INTO v_newest
  FROM public.map_events e
  WHERE e.user_id = v_uid
  ORDER BY e.created_at DESC, e.id DESC
  LIMIT 1;

  IF v_event.kind NOT IN ('claim', 'restore')
     OR v_newest IS DISTINCT FROM v_event.id
     OR v_event.created_at <= now() - interval '2 minutes' THEN
    RAISE EXCEPTION 'cannot undo';
  END IF;

  DELETE FROM public.map_events WHERE id = v_event.id;

  RETURN public.map_state(v_uid, p_tz);
END;
$$;

-- 5. Function grants ---------------------------------------------------------
REVOKE ALL ON FUNCTION public.map_check_tz(text) FROM public, anon, authenticated;
REVOKE ALL ON FUNCTION public.map_check_terrain(text) FROM public, anon, authenticated;
REVOKE ALL ON FUNCTION public.map_newest_owned(uuid) FROM public, anon, authenticated;
REVOKE ALL ON FUNCTION public.map_apply_decay(uuid, text) FROM public, anon, authenticated;
REVOKE ALL ON FUNCTION public.map_credits(uuid, text, timestamptz)
  FROM public, anon, authenticated;
REVOKE ALL ON FUNCTION public.map_state(uuid, text) FROM public, anon, authenticated;

REVOKE ALL ON FUNCTION public.map_open(text, text) FROM public, anon;
REVOKE ALL ON FUNCTION public.map_claim(text, int, int) FROM public, anon;
REVOKE ALL ON FUNCTION public.map_undo(text, bigint) FROM public, anon;
GRANT EXECUTE ON FUNCTION public.map_open(text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.map_claim(text, int, int) TO authenticated;
GRANT EXECUTE ON FUNCTION public.map_undo(text, bigint) TO authenticated;

COMMIT;
